import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header";
import Main from "@/Components/Main";
import Footer from "@/Components/Footer";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Sareen",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/logo.png", sizes: "32x32" }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} bg-white`}>
        <Header />
        <Main />
        {children}
        <Footer />
      </body>
    </html>
  );
}
