// app/layout.js
import "./globals.css";
import { LanguageProvider } from "./context/LanguageContext";
import LayoutWithLanguage from "./languageLayout";

export const metadata = {
  title: "Sareen",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: "/logo.png", sizes: "32x32" }],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Default dir and lang here, real logic goes inside client layout */}
      <body>
        <LanguageProvider>
          <LayoutWithLanguage>{children}</LayoutWithLanguage>
        </LanguageProvider>
      </body>
    </html>
  );
}
